server:
  port: 8002

spring:
  application:
    name: provider-dept
  datasource:
    url: jdbc:mysql://39.100.110.116:3306/cloudDB02?useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/**/*.xml


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
      #defaultZone: http://192.168.31.101:7001/myeu/
      #注意这里的defaultZone 不能写成default-zone，后面的eureka不能换成，其他的
      #字符串，这个eureka字符串是定死的。
