server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://39.100.110.116:3306/cloudDB01?useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/**/*.xml



